FROM python:3.12-slim

WORKDIR /app

COPY service-a/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy application code: service-a/app -> /app/app
COPY service-a/app ./app

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]